#Maintainer : Thibaud LE GALL
#thibaud.le.gall@devoteam.com

FROM debian:buster-slim AS slim-os

ARG TENSORFLOW_VERSION=2.3.1

# Install runtime dependencies
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    libboost-atomic1.67.0 \
    libboost-chrono1.67.0 \
    libboost-date-time1.67.0 \
    libboost-iostreams1.67.0 \
    libboost-python1.67.0 \
    libboost-regex1.67.0 \
    libboost-serialization1.67.0 \
    libboost-system1.67.0 \
    libboost-thread1.67.0 \
    libcairo2-dev \
    python3-dev \
    python3-numpy \
    python3-cairo \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

FROM slim-os

RUN apt-get update \
 && apt-get install -y \
	dos2unix \
	python3-pip \
	gcc git openssh-client less curl \
	libxtst-dev libxext-dev libxrender-dev libfreetype6-dev \
	libfontconfig1 libgtk2.0-0 libxslt1.1 libxxf86vm1 \
	libjpeg-dev zlib1g-dev libpng-dev \
	libgl1-mesa-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Creating a workdir and adding requirements
RUN mkdir /home/app

WORKDIR /home/app

COPY requirements.txt /home/app/requirements.txt

# Installing the dependencies
RUN pip3 --no-cache-dir install --ignore-installed --upgrade ipython && \
	pip3 install --upgrade pip && \
	pip3 --no-cache-dir install -r /home/app/requirements.txt \
		&& \
	python3 -m ipykernel.kernelspec


ARG PYCHARM_VERSION=2019.3
ARG PYCHARM_BUILD=2019.3.2
ARG pycharm_source=https://download.jetbrains.com/python/pycharm-community-${PYCHARM_BUILD}.tar.gz
ARG pycharm_local_dir=.PyCharm${PYCHARM_VERSION}

RUN mkdir /opt/pycharm && \
	cd /opt/pycharm
	
RUN curl -fsSL $pycharm_source -o /opt/pycharm/installer.tgz \
  && tar --strip-components=1 -xzf /opt/pycharm/installer.tgz \
  && rm /opt/pycharm/installer.tgz

#RUN useradd -ms /bin/bash newuser

RUN mkdir -p /home/app/.PyCharm \
  && ln -sf /home/app.PyCharm /home/app$pycharm_local_dir

#RUN chown newuser /home/app/

#USER newuser
	
WORKDIR /home/app